all: build_server create_server server_clean

build_server:
	@echo "Building client program"

create_server:
	@gcc -Wall -Wextra -pthread -o  dfs_client dfs_client.c

server_clean:
	@echo "Client built"


