all: build_server create_server server_clean

build_server:
	@echo "Building server program"

create_server:
	@gcc -Wall -Wextra -pthread -o  dfs_server dfs_server.c

server_clean:
	@echo "Server built"


